name: serverless-cd website deploy

on:
  push:
    branches:
      - main

jobs:
  Build-Deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Build
        run: |
          npm config set legacy-peer-deps true
          npm install
          npm run build
      - run: npm i @serverless-devs/s -g  --registry=https://registry.npmmirror.com
      - run: s config add --AccessKeyID ${{secrets.ACCESS_KEYID}}  --AccessKeySecret ${{secrets.ACCESS_KEYSECRET}} -a default -f
      - name: Deploy
        run: s deploy --use-local -y
